#!/bin/bash

#SBATCH --job-name=transUNet

### how much time, this job takes < one minute, we just put 1 hour
#SBATCH --time=06:00:00

### how much memory, 4 GB is plenty for this
#SBATCH --mem=16000

### how many processes in this job
#SBATCH --ntasks=1

### change the 1 below to match the # of cores needed
#SBATCH --cpus-per-task=1

#SBATCH --gres=gpu:P100:2

#SBATCH --partition=short,gpu

module load pytorch/1.6-cuda10
python main.py

exit 0
